
name: Run Python Script

on:
  schedule:
    # 每天凌晨 1 点运行
    - cron: '0 1 * * *'  # 你可以根据需要修改定时任务
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install yt-dlp
      run: |
        sudo apt-get update
        sudo apt-get install yt-dlp  # 安装 yt-dlp

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如果有其他依赖，安装它们

    - name: Run script
      run: |
        python yt.py  # 运行你的 Python 脚本

    - name: Commit results
      run: |
        git add result.log
        git commit -m "Add test results"
        git push origin main
